export const cartBadge = 'span[class="shopping_cart_badge"]'
export const addToCartButton = 'button[id^="add-to-cart-"]'
export const removeFromCartButton = 'button[id^="remove-"]'
export const sideMenuButton = 'button[id="react-burger-menu-btn"]'
export const logoutButton = 'a[id="logout_sidebar_link"]'