export const usernameField = 'input[name="user-name"]'
export const passwordField = 'input[name="password"]'
export const loginButton = 'input[name="login-button"]'
export const errorMessage = 'h3[data-test="error"]'
export const standard_user = "standard_user"
export const locked_out_user = "locked_out_user"
export const problem_user = "problem_user"
export const performance_glitch_user = "performance_glitch_user"
export const password = "secret_sauce"